#!/bin/bash

#android version
AV=android-8.0.0_r33
DIST=oreo
TARGET=eng
USERNAME="john doe"
USEREMAIL="jd@gmail.com"

#memory for the java VM
JMEM=1500m

#number of cpu
CPUS=$(grep ^processor /proc/cpuinfo | wc -l)

export PATH=$PATH:~/bin
# source ~/.bashrc

mkdir -p ~/bin ~/aosp/$DIST

wget 'https://storage.googleapis.com/git-repo-downloads/repo' -P ~/bin

chmod +x ~/bin/repo

git config --global user.name "$USERNAME"
git config --global user.email "$USEREMAIL"

# echo 'deb-src http://us.archive.ubuntu.com/ubuntu/ xenial main universe' >> /etc/apt/sources.list
# echo 'deb http://us.archive.ubuntu.com/ubuntu/ xenial main universe' >> /etc/apt/sources.list

apt update
apt install python2.7 openjdk-8-jdk android-tools-adb bc bison build-essential curl flex g++-multilib gcc-multilib gnupg gperf imagemagick lib32ncurses5-dev lib32readline-dev lib32z1-dev libesd0-dev liblz4-tool libncurses5-dev libsdl1.2-dev libssl-dev libwxgtk3.0-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc yasm zip zlib1g-dev


ln --force -s /usr/bin/python2.7 /usr/bin/python

cd ~/aosp/$DIST

repo init -u https://android.googlesource.com/platform/manifest -b $AV --depth=1

echo 'Starting repo sync at '$(date)
repo sync


echo '##*## HEY JJ HERE ##*##'
echo 'repo sync ended at '$(date)

export USE_CCACHE=1

prebuilts/misc/linux-x86/ccache/ccache -M 15G

export ANDROID_JACK_VM_ARGS="-Xmx$JMEM -Dfile.encoding=UTF-8 -XX:+TieredCompilation"

source build/envsetup.sh

lunch aosp_arm-$TARGET

make -j$CPUS

